-- Review Tabelle ergänzen


BEGIN;

-- ============================================================
-- AlgoRecall - Initial PostgreSQL Schema
-- ============================================================

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_id BIGINT NOT NULL UNIQUE,
    github_name TEXT NOT NULL,
    github_email TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE github_repository (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    github_repository_id BIGINT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_github_repository_user
        FOREIGN KEY (user_id)
        REFERENCES app_user(id)
        ON DELETE CASCADE
);

CREATE TABLE problem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL,
    external_id TEXT NOT NULL,
    problem_title TEXT NOT NULL,
    slug TEXT,
    source_url TEXT NOT NULL,

    CONSTRAINT uq_problem_source_external_id
        UNIQUE (source_id, external_id),

    CONSTRAINT fk_problem_source
        FOREIGN KEY (source_id)
        REFERENCES source(id)
        ON DELETE RESTRICT
);

CREATE TABLE leetcode_problem_content (
    problem_id BIGINT PRIMARY KEY,
    difficulty TEXT NOT NULL,
    description TEXT NOT NULL,
    examples JSONB NOT NULL,
    constraints JSONB NOT NULL,

    CONSTRAINT ck_leetcode_problem_content_difficulty
        CHECK (difficulty IN ('easy', 'medium', 'hard')),

    CONSTRAINT fk_leetcode_problem_content_problem
        FOREIGN KEY (problem_id)
        REFERENCES problem(id)
        ON DELETE CASCADE
);

CREATE TABLE user_problem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    problem_id BIGINT NOT NULL,
    status TEXT NOT NULL,
    confidence SMALLINT,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_user_problem_user_problem
        UNIQUE (user_id, problem_id),

    CONSTRAINT ck_user_problem_status
        CHECK (status IN ('attempted', 'solved')),

    CONSTRAINT ck_user_problem_confidence
        CHECK (confidence BETWEEN 1 AND 5),

    CONSTRAINT fk_user_problem_user
        FOREIGN KEY (user_id)
        REFERENCES app_user(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_user_problem_problem
        FOREIGN KEY (problem_id)
        REFERENCES problem(id)
        ON DELETE RESTRICT
);

CREATE TABLE tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_tag_user_name
        UNIQUE (user_id, name),

    CONSTRAINT fk_tag_user
        FOREIGN KEY (user_id)
        REFERENCES app_user(id)
        ON DELETE CASCADE
);

CREATE TABLE submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_problem_id BIGINT NOT NULL,
    repository_id BIGINT,
    github_path TEXT NOT NULL,
    github_blob_sha TEXT,
    external_submission_id TEXT,
    language TEXT NOT NULL,
    status TEXT NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uq_submission_user_problem_external_id
        UNIQUE (user_problem_id, external_submission_id),

    CONSTRAINT uq_submission_repository_path
        UNIQUE (repository_id, github_path),

    CONSTRAINT ck_submission_status
        CHECK (
            status IN (
                'accepted',
                'wrong_answer',
                'time_limit_exceeded',
                'memory_limit_exceeded',
                'runtime_error'
            )
        ),

    CONSTRAINT fk_submission_user_problem
        FOREIGN KEY (user_problem_id)
        REFERENCES user_problem(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_submission_repository
        FOREIGN KEY (repository_id)
        REFERENCES github_repository(id)
        ON DELETE SET NULL
);

CREATE TABLE user_problem_tag (
    user_problem_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,

    PRIMARY KEY (user_problem_id, tag_id),

    CONSTRAINT fk_user_problem_tag_user_problem
        FOREIGN KEY (user_problem_id)
        REFERENCES user_problem(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_user_problem_tag_tag
        FOREIGN KEY (tag_id)
        REFERENCES tag(id)
        ON DELETE CASCADE
);

CREATE TABLE submission_tag (
    submission_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,

    PRIMARY KEY (submission_id, tag_id),

    CONSTRAINT fk_submission_tag_submission
        FOREIGN KEY (submission_id)
        REFERENCES submission(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_submission_tag_tag
        FOREIGN KEY (tag_id)
        REFERENCES tag(id)
        ON DELETE CASCADE
);

COMMIT;
