
import os
from dotenv import load_dotenv

load_dotenv()


SESSION_SECRET = os.environ["SESSION_SECRET"]

GITHUB_CLIENT_ID = os.getenv("GITHUB_CLIENT_ID")
GITHUB_CLIENT_SECRET = os.getenv("GITHUB_CLIENT_SECRET")

GITHUB_AUTHORIZE_URL = os.getenv("GITHUB_AUTHORIZE_URL")
GITHUB_CALLBACK_URI = os.getenv("GITHUB_CALLBACK_URI")
GITHUB_ACCESS_TOKEN_URL = os.getenv("GITHUB_ACCESS_TOKEN_URL")
GITHUB_USER_URL = os.getenv("GITHUB_USER_URL")

FRONTEND_URL_AFTER_LOGIN = os.getenv("FRONTEND_URL_AFTER_LOGIN")